name: RuneChain
options:
  bundleIdPrefix: dev.u9g
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
targets:
  RuneChain:
    type: application
    platform: iOS
    sources:
      - path: RuneChain
      - path: ../web
        type: folder
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.u9g.runechain
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: RuneChain/Info.plist
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "5.0"
        ENABLE_USER_SCRIPT_SANDBOXING: YES
